openapi: 3.0.0
info:
  title: simple-api
  version: 0.1.0
x-kusk:
 upstream:
  service:
    name: smart-home-monolith
    namespace: default
    port: 8080
paths:
  /:
    get:
      x-kusk:
        upstream:
          service:
            name: smart-home-monolith
            namespace: default
            port: 8080
    post:
      x-kusk:
        upstream:
          service:
            name: smart-home-monolith
            namespace: default
            port: 8080