version: '3'
services:
  sensor1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      WEBSERVER_LISTEN: ":8081"
      SMART_HOME_ADDRESS: "http://gateway_in_kuber"
      SENSOR_ID: "sensor1"
  sensor2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      WEBSERVER_LISTEN: ":8082"
      SMART_HOME_ADDRESS: "http://gateway_in_kuber"
      SENSOR_ID: "sensor2"
  sensor3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      WEBSERVER_LISTEN: ":8083"
      SMART_HOME_ADDRESS: "http://gateway_in_kuber"
      SENSOR_ID: "sensor3"
