version: '3'
services:

  notificator:
    build:
      context: notificator
      dockerfile: Dockerfile
    environment:
      KAFKA_ADDR: "redpanda:9092"
      KAFKA_TOPIC: "temp_topic"
    depends_on:
      - redpanda
    networks:
      - smart-home-network

  temperature-manager:
    build:
      context: temperature-manager
      dockerfile: Dockerfile.temperature
    ports:
      - "7070:7070"
    environment:
      DATABASE_URI: "postgresql://postgres_user:postgres_password@postgres:5432/postgres_db?sslmode=disable"
      KAFKA_ADDR: "redpanda:9092"
      KAFKA_TOPIC: "temp_topic"
      WEBSERVER_ADDR: ":7070"
    depends_on:
      - postgres
      - redpanda
    networks:
      - smart-home-network

  sensor1:
    build:
      context: ../sensor
      dockerfile: Dockerfile
    ports:
      - "7170:80"
    environment:
      WEBSERVER_LISTEN: ":80"
      SMART_HOME_ADDRESS: "http://temperature-manager:7070"
      SENSOR_ID: "sensor1"
    networks:
      - smart-home-network
  sensor2:
    build:
      context: ../sensor
      dockerfile: Dockerfile
    ports:
      - "7171:80"
    environment:
      WEBSERVER_LISTEN: ":80"
      SMART_HOME_ADDRESS: "http://temperature-manager:7070"
      SENSOR_ID: "sensor2"
    networks:
      - smart-home-network
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    networks:
      - smart-home-network

  migrate:
    build:
      context: temperature-manager
      dockerfile: Dockerfile.migrate
    depends_on:
      - postgres
    environment:
      DATABASE_URI: "postgresql://postgres_user:postgres_password@postgres:5432/postgres_db?sslmode=disable"
    networks:
      - smart-home-network

  redpanda:
    image: redpandadata/redpanda:latest
    command:
      # - redpanda
      # - start
      # - --smp 1
      # - --overprovisioned
      # - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      # - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092

      - redpanda start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"  # External Kafka API
      - "9644:9644"    # Admin API
    networks:
      - smart-home-network
networks:
  smart-home-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16