
services:

  notificator:
    build:
      context: notificator
      dockerfile: Dockerfile
    environment:
      KAFKA_ADDR: "nsqlookupd:4161"
      KAFKA_TOPIC: "temp-topic"
    depends_on:
      - nsqlookupd
      - temperature-manager
    networks:
      - smart-home-network

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - smart-home-network
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      - smart-home-network
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      - smart-home-network

  temperature-manager:
    build:
      context: temperature-manager
      dockerfile: Dockerfile.temperature
    ports:
      - "7070:7070"
    environment:
      DATABASE_URI: "postgresql://postgres_user:postgres_password@postgres:5432/postgres_db?sslmode=disable"
      KAFKA_ADDR: "nsqd:4150"
      KAFKA_TOPIC: "temp-topic"
      WEBSERVER_ADDR: ":7070"
    depends_on:
      - postgres
      - nsqd
    networks:
      - smart-home-network

  sensor1:
    build:
      context: ../sensor
      dockerfile: Dockerfile
    ports:
      - "7170:80"
    environment:
      WEBSERVER_LISTEN: ":80"
      SMART_HOME_ADDRESS: "http://temperature-manager:7070"
      SENSOR_ID: "sensor1"
    networks:
      - smart-home-network
  sensor2:
    build:
      context: ../sensor
      dockerfile: Dockerfile
    ports:
      - "7171:80"
    environment:
      WEBSERVER_LISTEN: ":80"
      SMART_HOME_ADDRESS: "http://temperature-manager:7070"
      SENSOR_ID: "sensor2"
    networks:
      - smart-home-network
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    networks:
      - smart-home-network

  migrate:
    build:
      context: temperature-manager
      dockerfile: Dockerfile.migrate
    depends_on:
      - postgres
    environment:
      DATABASE_URI: "postgresql://postgres_user:postgres_password@postgres:5432/postgres_db?sslmode=disable"
    networks:
      - smart-home-network

networks:
  smart-home-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16